matrix:
  TEST:
    - dependencies
    - jest
    - lint
    - deploy

pipeline:
  dependencies:
    image: node:dubnium
    commands:
      - ./scripts/check-lockfile.sh
    when:
      matrix:
        TEST: dependencies
  jest:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile
      - yarn jest
    when:
      matrix:
        TEST: jest
  lint:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile
      - yarn lint && yarn pretty-check
    when:
      matrix:
        TEST: lint
  deploy:
    image: node:dubnium
    secrets: [gh_token, netlify_auth_token, netlify_site]
    commands:
      - yarn clean
      - yarn dist
      - './node_modules/.bin/netlify deploy --site $${NETLIFY_SITE} --message "Drone build: ${CI_BUILD_NUMBER}" --json > netlify_deployment_result.json'
      - node scripts/set-netlify-deployment-status.js
    when:
      event: [push, pull_request]
      matrix:
        TEST: deploy
