pipeline:
  dependencies:
    image: node:dubnium
    commands:
      - ./scripts/check-lockfile.sh

  lint:
    group: tests
    image: node:dubnium
    commands:
      - yarn lint && yarn pretty:check

  jest:
    group: tests
    image: node:dubnium
    commands:
      - yarn jest

  check-build:
    image: node:dubnium
    secrets: [gh_token]
    commands: node scripts/failcheck.js
    when:
      status: [success, failure]

  deploy-twigjs-preview:
    group: previews
    image: node:dubnium
    secrets: [gh_token, ecl_twig_auth_token, ecl_twig_js_site_id]
    commands:
      - yarn twing:clean
      - yarn twing:dist
      - 'yarn netlify deploy --site $${NETLIFY_SITE_ID} --alias ${DRONE_COMMIT_BRANCH} --message "Drone build: ${CI_BUILD_NUMBER}"'
      - node scripts/set-netlify-deployment-status.js
    environment:
      - DEPLOY_CONTEXT=preview/twig-js
    when:
      event: push
      status: [success, failure]
      branch:
        exclude:
          - master

  deploy-prod-js:
    image: node:dubnium
    secrets: [gh_token, ecl_twig_auth_token, ecl_twig_js_site_id]
    commands:
      - yarn twing:clean
      - yarn twing:dist
      - 'yarn netlify deploy --prod --site $${ECL_TWIG_JS_SITE_ID} --message "Drone build: ${CI_BUILD_NUMBER}"'
      - node scripts/set-netlify-deployment-status.js
    environment:
      - DEPLOY_CONTEXT=preview/twig-js
    when:
      branch: master
      event: push

  deploy-prod-php:
    image: roelofr/php-node
    secrets: [gh_token, ecl_twig_auth_token, ecl_twig_php_site_id]
    commands:
      - npm install -g n && n stable
      - yarn install
      - rm -rf netlify.toml
      - yarn php:install
      - yarn php:dist
      - 'yarn netlify deploy --prod --site $${ECL_TWIG_PHP_SITE_ID} --message "Drone build: ${CI_BUILD_NUMBER}"'
      - node scripts/set-netlify-deployment-status.js
    environment:
      - DEPLOY_CONTEXT=preview/twig-php
    when:
      branch: master
      event: push

  deploy-twigphp-preview:
    group: previews
    image: roelofr/php-node
    secrets: [gh_token, ecl_twig_auth_token, ecl_twig_php_site_id]
    commands:
      - npm install -g n && n stable
      - yarn install
      - rm -rf netlify.toml
      - yarn php:install
      - yarn php:dist
      - yarn diff
      - 'yarn netlify deploy --dir=php/dist --site $${NETLIFY_SITE_ID} --alias php-${DRONE_COMMIT_BRANCH} --message "Drone build: ${CI_BUILD_NUMBER}"'
      - node scripts/set-netlify-deployment-status.js
    environment:
      - DEPLOY_CONTEXT=preview/twig-php
    when:
      event: push
      status: [success, failure]
      branch:
        exclude:
          - master
