matrix:
  TEST:
    - dependencies
    - jest
    - lint

pipeline:
  dependencies:
    image: node:dubnium
    commands:
      - ./scripts/check-lockfile.sh
    when:
      matrix:
        TEST: dependencies
  jest:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile
      - yarn jest
    when:
      matrix:
        TEST: jest
  lint:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile
      - yarn lint && yarn pretty-check
    when:
      matrix:
        TEST: lint
