pipeline:
  deploy-preview:
    image: roelofr/php-node
    secrets: [gh_token, netlify_auth_token, netlify_site]
    commands:
      - npm cache clean -f && npm install -g n && n stable
      - yarn install
      - composer install --no-scripts
      - yarn dist:php
      - 'npx netlify deploy --site $${NETLIFY_SITE} --message "Drone build: ${CI_BUILD_NUMBER}" --json > netlify_deployment_result.json'
      - node scripts/set-netlify-deployment-status.js
    when:
      event: push
      status: [success, failure]
      branch:
        exclude:
          - master

  deploy-prod:
    image: node:dubnium
    secrets: [gh_token, netlify_auth_token, netlify_site]
    commands:
      - yarn clean
      - yarn dist
      - 'npx netlify deploy --prod --site $${NETLIFY_SITE} --message "Drone build: ${CI_BUILD_NUMBER}" --json > netlify_deployment_result.json'
      - node scripts/set-netlify-deployment-status.js
    when:
      branch: master
      event: push
