matrix:
  TEST:
    - jest
    - lint

pipeline:
  install:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile
  jest:
    image: node:dubnium
    commands:
      - yarn jest
    when:
      matrix:
        TEST: jest
  lint:
    image: node:dubnium
    commands:
      - yarn lint
    when:
      matrix:
        TEST: lint
