pipeline:
  dependencies:
    image: node:dubnium
    commands:
      - ./scripts/check-lockfile.sh

  jest:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile
      - yarn jest

  lint:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile
      - yarn lint && yarn pretty-check

  deploy-preview:
    image: node:dubnium
    secrets: [gh_token, netlify_auth_token, netlify_site]
    commands:
      - yarn clean
      - yarn dist
      - 'npx netlify deploy --site $${NETLIFY_SITE} --message "Drone build: ${CI_BUILD_NUMBER}" --json > netlify_deployment_result.json'
      - node scripts/set-netlify-deployment-status.js
    when:
      event: push
      branch:
        exclude:
          - master

  deploy-prod:
    image: node:dubnium
    secrets: [gh_token, netlify_auth_token, netlify_site]
    commands:
      - yarn clean
      - yarn dist
      - 'npx netlify deploy --prod --site $${NETLIFY_SITE} --message "Drone build: ${CI_BUILD_NUMBER}" --json > netlify_deployment_result.json'
      - node scripts/set-netlify-deployment-status.js
    when:
      branch: master
      event: push
