[build]
  command = "yarn dist"
  publish = "build"

[build.environment]
  YARN_VERSION = "1.12.3"
  YARN_FLAGS = "--frozen-lockfile"

[context."TWIG-158"]
  command = "yarn dist-php"
  publish = "php/dist"

