[build]
  command = "yarn dist"
  publish = "build"

[build.environment]
  YARN_VERSION = "1.12.3"
  YARN_FLAGS = "--frozen-lockfile"

[context.branch-deploy]
  command = "composer install && yarn dist:php"
  publish = "php/dist"
