<?php

use Webmozart\PathUtil\Path;

require_once __DIR__ . '/bootstrap.php';

$result_extension = '.php.html';
$extension = '.html.twig';
$output_folder = 'dist';
$system = getenv('ECL_SYSTEM');

$root_folder = __DIR__ . '/../../../..';
$root_folder_abs = Path::canonicalize($root_folder);

// The place to store HTML output of the Twig PHP renderer.
$system_path = $root_folder_abs . DIRECTORY_SEPARATOR . $output_folder . DIRECTORY_SEPARATOR . $system;

// This is a list of components, as generated by JavaScript.
// Thus, the list will contain only components for which we have demo data.
$components = array_slice(scandir(Path::canonicalize($system_path)), 2);

foreach ($components as $component) {
  $template = $component . $extension;
  $folder = Path::canonicalize($system_path . DIRECTORY_SEPARATOR . $component);

  // Get the list of data files.
  // For each data file the renderer will create an HTML file.
  $files = array_slice(scandir($folder), 2);

  foreach ($files as $file_name) {
    try {
      $variant = str_replace(
        '.json',
        '',
        str_replace('data', $component, $file_name)
      );

      $data_string = file_get_contents(
        $folder . DIRECTORY_SEPARATOR . $file_name
      );
      $data_json = json_decode($data_string, TRUE);
      $data_html = $twig->render($template, $data_json);

      file_put_contents(
        $folder . DIRECTORY_SEPARATOR . $variant . $result_extension,
        $data_html
      );
    } catch (exception $e) {
      throw new Exception($e);
    }
  }
}
